@extends('layouts.app')

@section('content')
<div class="max-w-4xl mx-auto px-6 py-8">

    <div class="bg-white rounded-lg shadow" style="padding: 3rem;">

        {{-- Header --}}
        <div class="border-b pb-6 mb-8">
            <h1 class="text-3xl font-bold text-gray-900">Privacy Policy</h1>
            <p class="text-sm text-gray-400 mt-2">Last updated: February 06, 2026</p>
        </div>

        {{-- Content with typography styles --}}
        <div class="text-gray-700 leading-relaxed space-y-10">

            {{-- Introduction --}}
            <section>
                <p class="mb-3">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            </section>

            {{-- Interpretation and Definitions --}}
            <section>
                <h2 class="text-2xl font-bold text-gray-900 mb-4">Interpretation and Definitions</h2>

                <h3 class="text-lg font-semibold text-gray-800 mt-6 mb-2">Interpretation</h3>
                <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                <h3 class="text-lg font-semibold text-gray-800 mt-6 mb-2">Definitions</h3>
                <p class="mb-3">For the purposes of this Privacy Policy:</p>
                <ul class="list-disc pl-8 space-y-3 text-gray-600">
                    <li><strong class="text-gray-800">Account</strong> — means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong class="text-gray-800">Affiliate</strong> — means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong class="text-gray-800">Company</strong> — (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to BAI.</li>
                    <li><strong class="text-gray-800">Cookies</strong> — are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong class="text-gray-800">Country</strong> — refers to: France.</li>
                    <li><strong class="text-gray-800">Device</strong> — means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                    <li><strong class="text-gray-800">Personal Data</strong> — (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
                    <li><strong class="text-gray-800">Service</strong> — refers to the Website.</li>
                    <li><strong class="text-gray-800">Service Provider</strong> — means any natural or legal person who processes the data on behalf of the Company.</li>
                    <li><strong class="text-gray-800">Usage Data</strong> — refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                    <li><strong class="text-gray-800">Website</strong> — refers to BAI.</li>
                    <li><strong class="text-gray-800">You</strong> — means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
                </ul>
            </section>

            {{-- Collecting and Using Your Personal Data --}}
            <section>
                <h2 class="text-2xl font-bold text-gray-900 mb-4">Collecting and Using Your Personal Data</h2>

                <h3 class="text-lg font-semibold text-gray-800 mt-6 mb-2">Types of Data Collected</h3>

                <h4 class="font-semibold text-gray-800 mt-4 mb-2">Personal Data</h4>
                <p class="mb-3">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul class="list-disc pl-8 space-y-1 text-gray-600">
                    <li>Email address</li>
                    <li>First name and last name</li>
                </ul>

                <h4 class="font-semibold text-gray-800 mt-6 mb-2">Usage Data</h4>
                <p class="mb-3">Usage Data is collected automatically when using the Service.</p>
                <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

                <h4 class="font-semibold text-gray-800 mt-6 mb-2">Tracking Technologies and Cookies</h4>
                <p class="mb-3">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
                <ul class="list-disc pl-8 space-y-2 text-gray-600">
                    <li><strong class="text-gray-800">Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
                    <li><strong class="text-gray-800">Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email.</li>
                </ul>

                <p class="mt-4 mb-3">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                <p class="mb-4">Where required by law, we use non-essential cookies only with Your consent. You can withdraw or change Your consent at any time.</p>

                <p class="mb-3 font-medium text-gray-800">We use both Session and Persistent Cookies for the purposes set out below:</p>
                <div class="border rounded-lg divide-y">
                    <div class="p-4">
                        <p class="font-semibold text-gray-800">Necessary / Essential Cookies</p>
                        <p class="text-xs text-gray-400 mt-1">Session Cookies &bull; Administered by: Us</p>
                        <p class="text-sm mt-2">These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</p>
                    </div>
                    <div class="p-4">
                        <p class="font-semibold text-gray-800">Cookies Policy / Notice Acceptance Cookies</p>
                        <p class="text-xs text-gray-400 mt-1">Persistent Cookies &bull; Administered by: Us</p>
                        <p class="text-sm mt-2">These Cookies identify if users have accepted the use of cookies on the Website.</p>
                    </div>
                    <div class="p-4">
                        <p class="font-semibold text-gray-800">Functionality Cookies</p>
                        <p class="text-xs text-gray-400 mt-1">Persistent Cookies &bull; Administered by: Us</p>
                        <p class="text-sm mt-2">These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.</p>
                    </div>
                </div>
            </section>

            {{-- Use of Your Personal Data --}}
            <section>
                <h3 class="text-lg font-semibold text-gray-800 mb-3">Use of Your Personal Data</h3>
                <p class="mb-3">The Company may use Personal Data for the following purposes:</p>
                <ul class="list-disc pl-8 space-y-2 text-gray-600">
                    <li><strong class="text-gray-800">To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                    <li><strong class="text-gray-800">To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                    <li><strong class="text-gray-800">For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                    <li><strong class="text-gray-800">To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                    <li><strong class="text-gray-800">To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer.</li>
                    <li><strong class="text-gray-800">To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                    <li><strong class="text-gray-800">For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                    <li><strong class="text-gray-800">For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, and to evaluate and improve our Service.</li>
                </ul>

                <p class="mt-6 mb-3">We may share Your Personal Data in the following situations:</p>
                <ul class="list-disc pl-8 space-y-2 text-gray-600">
                    <li><strong class="text-gray-800">With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service.</li>
                    <li><strong class="text-gray-800">For business transfers:</strong> We may share or transfer Your Personal Data in connection with any merger, sale of Company assets, financing, or acquisition.</li>
                    <li><strong class="text-gray-800">With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
                    <li><strong class="text-gray-800">With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
                    <li><strong class="text-gray-800">With other users:</strong> When You share Personal Data or otherwise interact in public areas with other users, such information may be viewed by all users.</li>
                    <li><strong class="text-gray-800">With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
                </ul>
            </section>

            {{-- Retention --}}
            <section>
                <h3 class="text-lg font-semibold text-gray-800 mb-3">Retention of Your Personal Data</h3>
                <p class="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>

                <div class="border rounded-lg divide-y">
                    <div class="p-4">
                        <p class="font-semibold text-gray-800">Account Information</p>
                        <p class="text-sm mt-1">User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure.</p>
                    </div>
                    <div class="p-4">
                        <p class="font-semibold text-gray-800">Customer Support Data</p>
                        <p class="text-sm mt-1">Support tickets and correspondence: up to 24 months from the date of ticket closure. Chat transcripts: up to 24 months for quality assurance.</p>
                    </div>
                    <div class="p-4">
                        <p class="font-semibold text-gray-800">Usage Data</p>
                        <p class="text-sm mt-1">Website analytics data: up to 24 months from the date of collection. Server logs: up to 24 months for security monitoring.</p>
                    </div>
                </div>
            </section>

            {{-- Transfer --}}
            <section>
                <h3 class="text-lg font-semibold text-gray-800 mb-3">Transfer of Your Personal Data</h3>
                <p class="mb-3">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.</p>
                <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>
            </section>

            {{-- Delete --}}
            <section>
                <h3 class="text-lg font-semibold text-gray-800 mb-3">Delete Your Personal Data</h3>
                <p class="mb-3">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
                <p>You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section.</p>
            </section>

            {{-- Disclosure --}}
            <section>
                <h3 class="text-lg font-semibold text-gray-800 mb-3">Disclosure of Your Personal Data</h3>

                <h4 class="font-semibold text-gray-800 mt-4 mb-2">Business Transactions</h4>
                <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred.</p>

                <h4 class="font-semibold text-gray-800 mt-4 mb-2">Law enforcement</h4>
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

                <h4 class="font-semibold text-gray-800 mt-4 mb-2">Other legal requirements</h4>
                <p class="mb-3">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <ul class="list-disc pl-8 space-y-1 text-gray-600">
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                </ul>
            </section>

            {{-- Security --}}
            <section>
                <h3 class="text-lg font-semibold text-gray-800 mb-3">Security of Your Personal Data</h3>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            </section>

            {{-- Children --}}
            <section>
                <h2 class="text-2xl font-bold text-gray-900 mb-4">Children's Privacy</h2>
                <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16.</p>
            </section>

            {{-- Links --}}
            <section>
                <h2 class="text-2xl font-bold text-gray-900 mb-4">Links to Other Websites</h2>
                <p>Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            </section>

            {{-- Changes --}}
            <section>
                <h2 class="text-2xl font-bold text-gray-900 mb-4">Changes to this Privacy Policy</h2>
                <p class="mb-3">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes.</p>
            </section>

            {{-- Contact --}}
            <section>
                <h2 class="text-2xl font-bold text-gray-900 mb-4">Contact Us</h2>
                <p class="mb-3">If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul class="list-disc pl-8 text-gray-600">
                    <li>By email: <span class="text-blue-600">contact@bai.com</span></li>
                </ul>
            </section>

        </div>
    </div>
</div>
@endsection
